---
title: "Capítulo 3"
author: "Pedro Pablo Villegas"
date: "27/9/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# von Neumann (1946)

* Semilla con 5 dígitos
* Elevar al cuadrado con 10 dígitos (poner ceros iniciales si se necesita)
* Seleccionar los 5 números centrales
* Comenzar nuevamente

```{r, eval=TRUE, echo=TRUE}

```



```{r cars, eval=FALSE, include=FALSE}
#est <- c(165, 187, 156, 162, 158,
         164, 170, 160, 185, 175)

peso <- c(55, 96, 50, 59, 58, 84,
          50, 90, 80)

plot(x = est, y = peso, pch = 20)
rug(x = est, col = "red")

plot(density/(est))

# simulacion

n <- 500

est.r <- runif(n = n, min = 150, max = 200)
media <- -194 + 1.55*est.r
peso.r <- rnorm(n = n, mean = media, sd = 6.1)
plot()

mod.r <- lm(peso ~ est.r)
summary(mod.r)


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
